### ISSUE TITLE
add torrent list  in web pages using gh-pages

### ISSUE THREAD

**Issue by siddht4** [Strit/manjaro-torrents#1]
Please add all the torrent links in gh-pages rather than in master and simply put those urls in https://manjaro.org/.

Example :   directly attach   manajro 17.1.6  mate community edition in the main page    using the link  
 https://linux-dntt1.github.io/manjaro-torrents/community/mate/17.1.6/manjaro-mate-17.1.6-stable-x86_64.iso.torrent

**Comment by Strit** [comment]
I don't have any write access to https://manjaro.org. This is only a backup location for the torrent files. It's not meant as a main repo for torrents. That is on OSDN and Sourceforge.

So we would have to get Phil to do this I think.
I already created the "gh-pages" part, but the main links will probably still be the OSDN/SF ones.

**Comment by siddht4** [comment]
this was only meant for torrent link which directs to  yours repo.So it would be more easier to just share a link of torrent file accessible by web aka gh-pages or directly web publishing your master directory.

**Comment by Strit** [comment]
As I said before, the Manjaro Team manages the links on the manjaro.org webpage. I just create the torrents and uploads it to the places I have access. 🙂

**Comment by Strit** [comment]
Closing this, as I have done what I can to fascilitate this request.
